### ISSUE TITLE
Ability to select all media

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-media#152] opened 2023-09-11 04:37 UTC
The way Media Viewer is implemented, it is very hard to choose multiple images to download. Here are a few usecases that require bulk download that are missing

- There are about 30 images to be downloaded, which spans across 2 pages
- I need to provide a specific image for an entire district for a report

To handle the above scenarios, the following are required

### Acceptance criteria
- Selections should persist across screens when moving previous/next. 
- A "Select All" option should be provided for selecting items within the page. 
- Select All should uncover an option to "Select all pages" (similar to experience in Task Assignment) where the user can choose to download all items upto 1000. Ensure that the number of images from all pages should still be < 1000.
- Download should download all selected items.
- Selection of a image with a name say 'abc', selects all the images with the same name 'abc'. This bug needs to be fixed.

**Comment by mahalakshme** [comment] 2023-09-19 05:35
@ashusvnath ve added the bug discussed in standup as part of AC here.

**Comment by ashusvnath** [comment] 2023-09-19 11:00
@mahalakshme : I will keep a lookout for that issue.

**Comment by ashusvnath** [comment] 2023-09-19 11:01
On discussions with @vinayvenu . It has been decided to use "Select all pages" instead of "Select first 1000". And give a warning to the user in case all selected pages contain > 1000 images.

**Comment by vinayvenu** [comment] 2023-09-19 11:54
Cc @mahalakshme

**Comment by 1t5j0y** [comment] 2023-09-25 06:20
Tested on rwbnitiuat org on prerelease.

QA comments:

1. This acceptance criteria has not been done - "Selection of a image with a name say 'abc', selects all the images with the same name 'abc'. This bug needs to be fixed."
https://github.com/avniproject/avni-media/assets/54208632/f402f076-2e47-49fc-a35f-70c553c96f3a
2. UI - The text currently shown on the button to select images across all pages is "Select All Media Matching Filter" which isn't very clear. Something like "Select Media On All Pages" might be clearer. 
3. UI - 'Clear selection' button is currently only shown if the user has selected images across multiple images. It should also be applicable if the user has only made selections on the current page.
 
Have not tested more than 1000 images scenario due to lack of data.

**Comment by 1t5j0y** [comment] 2023-09-25 07:29
Additionally, selected all media across all pages and issued a download request but a few hours later, the status of the download job is still pending. Unsure if related to this card.

**Comment by ashusvnath** [comment] 2023-09-25 07:31
@1t5j0y : The job never got captured because `etl` needed to be deployed. The download all media end-point is on etl because that is the source of image URL's.  A deploy to pre-release should fix the issue.

**Comment by ashusvnath** [comment] 2023-09-25 07:34
> Tested as achala@rwbnitiuat on prerelease.
> 
> QA comments:
> 
> 1. This acceptance criteria has not been done - "Selection of a image with a name say 'abc', selects all the images with the same name 'abc'. This bug needs to be fixed."
>    https://github.com/avniproject/avni-media/assets/54208632/f402f076-2e47-49fc-a35f-70c553c96f3a
> 2. UI - The text currently shown on the button to select images across all pages is "Select All Media Matching Filter" which isn't very clear. Something like "Select Media On All Pages" might be clearer.
> 3. UI - 'Clear selection' button is currently only shown if the user has selected images across multiple images. It should also be applicable if the user has only made selections on the current page.
> 4. Following flow has some confusing UI behaviour:
>    Select all on page 1 of search results
>    Navigate to page 2 - 'Select all' checkbox shows as empty i.e. no current selection
>    Click on select all - First click does not do anything. The button (and images on page 2) gets selected only on second click.
>    https://github.com/avniproject/avni-media/assets/54208632/66c62607-2b10-4d1f-841f-783245da9513
> 
> Have not tested more than 1000 images scenario due to lack of data.

Based on discussion with @vinayvenu 

1. Will be addressed
2. Is not a priority
3. Is not a priority
4. Will be fixed

**Comment by 1t5j0y** [comment] 2023-09-25 08:37
Re: https://github.com/avniproject/avni-media/issues/152#issuecomment-1733080453
latest etl 5.0 branch is deployed to prerelease but observing the same behaviour i.e. 'download all' requests remain in pending state

**Comment by vinayvenu** [comment] 2023-09-25 08:55
@ashusvnath this looks like a problem with submitting the job for download.

**Comment by ashusvnath** [comment] 2023-09-25 09:21
@vinayvenu , @1t5j0y : There's a bunch of queued jobs because the local FS folder creation for concept name `NOC/Work order image` is failing. Note the `/` in the concept name. This was discovered thanks to @himeshr .

**Comment by vinayvenu** [comment] 2023-09-27 06:10
- Add AVNI_MEDIA_SERVER_DOWNLOAD_URL
- Ensure this is available on staging

**Comment by ashusvnath** [comment] 2023-09-28 06:46
AVNI_MEDIA_SERVER_DOWNLOAD_URL has been added to code and the 5.0 release card has been updated with section talking about etl deployment for 5.0.

**Comment by ashusvnath** [comment] 2023-09-28 07:57
Latest changes have been deployed to staging also.

**Comment by 1t5j0y** [comment] 2023-09-28 09:30
Retested and verified fixes.

**Comment by mahalakshme** [comment] 2023-09-28 10:04
@ashusvnath @vinayvenu  I tried to do some sanity testing before releasing, Found a bug:
Steps to reproduce:
- Click on 'Select All'
- Click on 'Select all Media Matching filter'
- Unselect one image
- The selection from 2nd page sometimes goes off, sometimes it is from 3rd page.

https://github.com/avniproject/avni-media/assets/10369963/2b3a0073-7e4d-4022-a0a1-40cd99a90087

**Comment by vinayvenu** [comment] 2023-09-28 10:11
@mahalakshme we can fix this as a separate bug.

**Closed** 2023-09-28 11:09 UTC
